const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const roleNames={almacenista:'Almacenista',coordinador:'Coordinador de área',gerente:'Gerente',edi:'Usuario EDI'};
const restrictedRoles=['coordinador','gerente','edi'];
let activeUser={name:'',role:''};
let productos=JSON.parse(localStorage.getItem('inventro_productos')||'null')||[
{id:1,codigo:'P001',nombre:'Tubería de polietileno',categoria:'Materiales',cantidad:35,minimo:10,precio:8500},
{id:2,codigo:'P002',nombre:'Válvula de gas',categoria:'Materiales',cantidad:18,minimo:8,precio:12500},
{id:3,codigo:'P003',nombre:'Detector de fugas',categoria:'Equipos',cantidad:6,minimo:5,precio:185000},
{id:4,codigo:'P004',nombre:'Regulador de presión',categoria:'Equipos',cantidad:4,minimo:8,precio:32000},
{id:5,codigo:'P005',nombre:'Medidor de gas',categoria:'Herramientas',cantidad:9,minimo:5,precio:12000}
];
let movimientos=JSON.parse(localStorage.getItem('inventro_movimientos')||'null')||[];
let usuarios=JSON.parse(localStorage.getItem('inventro_usuarios')||'null')||[
{id:1,nombre:'Eduar',rol:'almacenista',password:'1234'},
{id:2,nombre:'Carlos',rol:'coordinador',password:'1234'},
{id:3,nombre:'Laura',rol:'gerente',password:'1234'}
];
let settings=JSON.parse(localStorage.getItem('inventro_settings')||'null')||{systemName:'INVENTRO',welcomeMessage:'Bienvenido al Sistema de Control de Inventarios',defaultMinStock:5,maintenance:'off'};
const save=()=>{localStorage.setItem('inventro_productos',JSON.stringify(productos));localStorage.setItem('inventro_movimientos',JSON.stringify(movimientos));localStorage.setItem('inventro_usuarios',JSON.stringify(usuarios));localStorage.setItem('inventro_settings',JSON.stringify(settings));};
function toast(m){const t=$('#toast');t.textContent=m;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2600)}
function canEdit(){return !restrictedRoles.includes(activeUser.role)}
function renderAll(){renderDashboard();renderProducts();renderInventory();renderMovementSelect();renderMovements();renderUsers();}
function renderDashboard(){ $('#totalProductos').textContent=productos.length;$('#totalEntradas').textContent=movimientos.filter(x=>x.tipo==='Entrada').length;$('#totalSalidas').textContent=movimientos.filter(x=>x.tipo==='Salida').length;$('#stockBajo').textContent=productos.filter(x=>x.cantidad<=x.minimo).length;$('#recentMovements').innerHTML=movimientos.slice(-6).reverse().map(m=>`<tr><td>${m.fecha}</td><td>${m.producto}</td><td>${m.tipo}</td><td>${m.cantidad}</td><td>${m.usuario}</td></tr>`).join('')||'<tr><td colspan="5">No hay movimientos registrados.</td></tr>';}
function renderProducts(filter=''){let p=productos.filter(x=>(x.nombre+x.codigo).toLowerCase().includes(filter.toLowerCase()));$('#productsTable').innerHTML=p.map(x=>`<tr><td>${x.codigo}</td><td>${x.nombre}</td><td>${x.categoria}</td><td>${x.cantidad}</td><td>${canEdit()?`<button class="action-btn edit-btn" onclick="editProduct(${x.id})">Editar</button><button class="action-btn delete-btn" onclick="deleteProduct(${x.id})">Eliminar</button>`:'Solo consulta'}</td></tr>`).join('');}
function renderInventory(filter=''){let p=productos.filter(x=>(x.nombre+x.codigo).toLowerCase().includes(filter.toLowerCase()));$('#inventoryTable').innerHTML=p.map(x=>`<tr><td>${x.codigo}</td><td>${x.nombre}</td><td>${x.cantidad}</td><td>${x.minimo}</td><td class="${x.cantidad<=x.minimo?'status-low':'status-ok'}">${x.cantidad<=x.minimo?'Stock bajo':'Disponible'}</td></tr>`).join('');}
function renderMovementSelect(){$('#movProducto').innerHTML=productos.map(x=>`<option value="${x.id}">${x.nombre} (${x.cantidad} disponibles)</option>`).join('')}
function renderMovements(){$('#movementsTable').innerHTML=movimientos.slice().reverse().map(m=>`<tr><td>${m.fecha}</td><td>${m.producto}</td><td>${m.tipo}</td><td>${m.cantidad}</td></tr>`).join('')||'<tr><td colspan="4">Sin movimientos.</td></tr>'}
function renderUsers(){$('#usersTable').innerHTML=usuarios.map(u=>`<tr><td>${u.nombre}</td><td>${roleNames[u.rol]}</td><td><button class="action-btn edit-btn" onclick="editUser(${u.id})">Cambiar contraseña / editar</button><button class="action-btn delete-btn" onclick="deleteUser(${u.id})">Eliminar</button></td></tr>`).join('')}
function showSection(id){if(restrictedRoles.includes(activeUser.role)&&!['dashboard','inventario','reportes'].includes(id)){toast('Este rol tiene acceso únicamente a existencias y reportes.');return}$$('.page-section').forEach(s=>s.classList.remove('active-section'));$('#'+id).classList.add('active-section');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===id));}
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();activeUser={name:$('#usuario').value.trim(),role:$('#rol').value};$('#usuarioActivo').textContent=activeUser.name;$('#rolActivo').textContent=roleNames[activeUser.role];$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');document.body.classList.toggle('restricted',restrictedRoles.includes(activeUser.role));$('#restrictedNotice').classList.toggle('hidden',canEdit());renderAll();showSection('dashboard');});
$('#logoutBtn').onclick=()=>{activeUser={name:'',role:''};$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden');document.body.classList.remove('restricted');$('#loginForm').reset();};
$$('[data-section]').forEach(b=>b.onclick=()=>showSection(b.dataset.section));
$('#showProductForm').onclick=()=>{$('#productForm').reset();$('#editProductId').value='';$('#productFormTitle').textContent='Registrar producto';$('#productFormPanel').classList.remove('hidden')};
$('#closeProductForm').onclick=$('#cancelProduct').onclick=()=>$('#productFormPanel').classList.add('hidden');
$('#productForm').addEventListener('submit',e=>{e.preventDefault();if(!canEdit())return toast('No tiene permisos para modificar productos.');let id=+$('#editProductId').value;let data={codigo:$('#codigo').value,nombre:$('#nombreProducto').value,categoria:$('#categoria').value,cantidad:+$('#cantidad').value,minimo:+$('#stockMinimo').value,precio:+$('#precio').value};if(id){productos=productos.map(p=>p.id===id?{...p,...data}:p);toast('Producto actualizado correctamente.')}else{productos.push({id:Date.now(),...data});toast('Producto registrado correctamente.')}save();renderAll();$('#productFormPanel').classList.add('hidden')});
window.editProduct=id=>{if(!canEdit())return;let p=productos.find(x=>x.id===id);$('#editProductId').value=p.id;$('#codigo').value=p.codigo;$('#nombreProducto').value=p.nombre;$('#categoria').value=p.categoria;$('#cantidad').value=p.cantidad;$('#stockMinimo').value=p.minimo;$('#precio').value=p.precio;$('#productFormTitle').textContent='Modificar producto';$('#productFormPanel').classList.remove('hidden')};
window.deleteProduct=id=>{if(!canEdit())return;if(confirm('¿Desea eliminar este producto?')){productos=productos.filter(p=>p.id!==id);save();renderAll();toast('Producto eliminado.')}};
$('#buscarProducto').oninput=e=>renderProducts(e.target.value);$('#buscarInventario').oninput=e=>renderInventory(e.target.value);
$('#movFecha').value=new Date().toISOString().slice(0,10);$('#movementForm').addEventListener('submit',e=>{e.preventDefault();if(!canEdit())return toast('No tiene permisos para registrar movimientos.');let p=productos.find(x=>x.id===+$('#movProducto').value),tipo=$('#movTipo').value,c=+$('#movCantidad').value;if(tipo==='Salida'&&c>p.cantidad)return toast('La salida supera las existencias disponibles.');p.cantidad+=tipo==='Entrada'?c:-c;movimientos.push({fecha:$('#movFecha').value,producto:p.nombre,tipo,cantidad:c,usuario:activeUser.name});save();renderAll();$('#movCantidad').value='';toast('Movimiento registrado correctamente.')});
$('#generateReport').onclick=()=>{let type=$('#reportType').value;let html=type==='inventario'?`<h3>Reporte de inventario actual</h3><div class="table-wrapper"><table><thead><tr><th>Código</th><th>Producto</th><th>Existencias</th></tr></thead><tbody>${productos.map(p=>`<tr><td>${p.codigo}</td><td>${p.nombre}</td><td>${p.cantidad}</td></tr>`).join('')}</tbody></table></div>`:`<h3>Reporte de movimientos</h3><div class="table-wrapper"><table><thead><tr><th>Fecha</th><th>Producto</th><th>Tipo</th><th>Cantidad</th></tr></thead><tbody>${movimientos.map(m=>`<tr><td>${m.fecha}</td><td>${m.producto}</td><td>${m.tipo}</td><td>${m.cantidad}</td></tr>`).join('')||'<tr><td colspan="4">Sin movimientos</td></tr>'}</tbody></table></div>`;$('#reportResult').innerHTML=html;$('#reportResult').classList.remove('hidden');toast('Reporte generado correctamente.')};
$('#printReport').onclick=()=>{if($('#reportResult').classList.contains('hidden'))return toast('Primero genere un reporte.');window.print()};
$('#openUsers').onclick=()=>{$('#usersPanel').classList.remove('hidden');$('#settingsPanel').classList.add('hidden');renderUsers()};$('#openSettings').onclick=()=>{$('#settingsPanel').classList.remove('hidden');$('#usersPanel').classList.add('hidden');$('#systemName').value=settings.systemName;$('#welcomeMessage').value=settings.welcomeMessage;$('#defaultMinStock').value=settings.defaultMinStock;$('#maintenance').value=settings.maintenance};
$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden'));
$('#userForm').addEventListener('submit',e=>{e.preventDefault();let id=+$('#editUserId').value;let d={nombre:$('#newUserName').value.trim(),rol:$('#newUserRole').value,password:$('#newUserPassword').value};if(id){usuarios=usuarios.map(u=>u.id===id?{...u,...d}:u);toast('Usuario y contraseña actualizados.')}else{usuarios.push({id:Date.now(),...d});toast('Nuevo usuario agregado correctamente.')}save();renderUsers();$('#userForm').reset();$('#editUserId').value=''});
$('#cancelUser').onclick=()=>{$('#userForm').reset();$('#editUserId').value=''};
window.editUser=id=>{let u=usuarios.find(x=>x.id===id);$('#editUserId').value=u.id;$('#newUserName').value=u.nombre;$('#newUserRole').value=u.rol;$('#newUserPassword').value=u.password;$('#usersPanel').scrollIntoView({behavior:'smooth'})};window.deleteUser=id=>{if(confirm('¿Desea eliminar este usuario?')){usuarios=usuarios.filter(u=>u.id!==id);save();renderUsers();toast('Usuario eliminado.')}};
$('#settingsForm').addEventListener('submit',e=>{e.preventDefault();settings={systemName:$('#systemName').value,welcomeMessage:$('#welcomeMessage').value,defaultMinStock:+$('#defaultMinStock').value,maintenance:$('#maintenance').value};save();document.querySelector('.brand strong').textContent=settings.systemName;$('#dashboardText').textContent=settings.welcomeMessage;toast('Configuración guardada correctamente.')});
